<?php

/**
 * Implements hook_theme().
 */
function inline_image_attach_entity_presave($entity, $type) {
  // Get configuration settings.
  $settings = \Drupal::config('inline_image_attach.settings');
  $typeId = $entity->getEntityTypeId();
  if (isset($typeId)) {
    // If the entity we are saving is a node type.
    if ($typeId == 'node' && !empty($settings)) {
      // Convert type to machine name.
      $type = str_replace(' ', '_', strtolower($entity->type->target_id));
      // Get the correct settings for this type.
      $iia_wysiwyg = $settings->get('iia_wysiwyg_' . $type);
      $iia_image = $settings->get('iia_image_' . $type);
      // Match any image URL's.
      preg_match_all('~<img.*?src=["\']+(.*?)["\']+~', $entity->{$iia_wysiwyg}->value, $urls);
      $result = array();
      foreach ($urls[1] as $path) {
        // Query the database for any inline images that match this URL
        $filename = basename($path);
        $uri = 'public://inline-images/' . urldecode($filename);
        $query = \Drupal::entityQuery('file');
        $query->condition('uri', $uri, '=');
        $result[] = $query->execute();
      }
      $files = array();
      // Load each file and place in the files array.
      foreach ($result as $f) {
        $files[] = entity_load('file', array_shift($f));
      }
      $existing_files = array();
      // Grab any existing files on the image field.
      foreach ($entity->{$iia_image}->getIterator() as $delta => $image) {
        array_push($existing_files, $image->target_id);
      }
      // Only add the file if it does not already exist on the image field.
      foreach ($files as $file) {
        if (!in_array($file->fid->value, $existing_files)) {
          $entity->{$iia_image}[] = $file->id();
        }
      }
    }
  }
}
